"""Cut a sprite out of a flat-colour background and embed it for the animator.

Usage: python3 cutout.py <input image> <output.png> [<output.js>] [--tol 40] [--bg R,G,B]

The background colour defaults to the top-left pixel. Every connected region of near-background
pixels that contains at least 25 exact background pixels is removed: that catches the outer
background and enclosed pockets (between a staff and a cape) while keeping small light details
such as fur highlights that happen to match the background. With an output.js path the PNG is
also written as a base64 data URI (`const SPRITE_PNG = ...`), so the page works from file://
without canvas tainting.
"""
import base64
import io
import sys
from collections import deque

from PIL import Image


def cutout(src, tol=40, bg=None):
    im = Image.open(src).convert('RGBA')
    W, H = im.size
    px = im.load()
    bg = bg or px[0, 0][:3]
    dist = lambda c: sum(abs(a - b) for a, b in zip(c[:3], bg))
    seen = set()
    for sy in range(H):
        for sx in range(W):
            if (sx, sy) in seen or dist(px[sx, sy]) > tol:
                continue
            comp, q = [], deque([(sx, sy)])
            seen.add((sx, sy))
            while q:
                x, y = q.popleft()
                comp.append((x, y))
                for n in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
                    if 0 <= n[0] < W and 0 <= n[1] < H and n not in seen and dist(px[n]) <= tol:
                        seen.add(n)
                        q.append(n)
            if sum(1 for p in comp if dist(px[p]) == 0) >= 25:
                for p in comp:
                    px[p] = (0, 0, 0, 0)
    return im


def main(argv):
    args, tol, bg = [], 40, None
    it = iter(argv)
    for a in it:
        if a == '--tol':
            tol = int(next(it))
        elif a == '--bg':
            bg = tuple(int(v) for v in next(it).split(','))
        else:
            args.append(a)
    if len(args) < 2:
        sys.exit(__doc__)
    im = cutout(args[0], tol, bg)
    im.save(args[1])
    if len(args) > 2:
        buf = io.BytesIO()
        im.save(buf, 'PNG', optimize=True)
        b64 = base64.b64encode(buf.getvalue()).decode()
        with open(args[2], 'w') as f:
            f.write("'use strict';\n/* Generated by tools/cutout.py from %s. */\nconst SPRITE_PNG = 'data:image/png;base64,%s';\n" % (args[0].split('/')[-1], b64))


if __name__ == '__main__':
    main(sys.argv[1:])
